name: Testing Platform
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'platform/**'
      - '.github/workflows/python.yml'
concurrency:
  group: platform-checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  black:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: poetry install
      - name: Run black check
        run: poetry run black --check .

  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: poetry install
      - name: Run mypy check
        run: poetry run mypy .

  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    services:
      reworkd_platform-db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "reworkd_platform"
          MYSQL_DATABASE: "reworkd_platform"
        options: >-
          --health-cmd="mysqladmin ping -u root --password=reworkd_platform"
          --health-interval=15s
          --health-timeout=5s
          --health-retries=6
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: poetry install
      - name: Run pytest check
        run: poetry run pytest -vv --cov="reworkd_platform" .
        env:
          REWORKD_PLATFORM_HOST: "0.0.0.0"
          REWORKD_PLATFORM_DB_HOST: localhost
          REWORKD_PLATFORM_KAFKA_BOOTSTRAP_SERVERS: '["localhost:9092"]'
